### ISSUE TITLE
log.txt is not being written to

### ISSUE THREAD

**Issue by celebratedsummer** [chippydip/HearthLog#14]
Hi, it has been a long time since I've filed a bug report.  Hearthlog worked perfectly for about a month for me.  I stopped watching it and just let it log away, but when I check now, it seems that it stopped logging on January 8.

After playing some games, the log.txt is:
18:50:46: Hearth Log v0.2.1
18:50:46: C:\Program Files (x86)\Hearthstone\Hearthstone.exe v1.0.0.4482
The time above is correct.  When I start Hearth Log.exe, it writes the above, but no more as I play a game, or do anything else.  When I restart Hearth Log.exe, it overwrites the above, with of course a new timestamp.

The Logged subdir is empty, and the Uploaded subdir has my old games, ending on Jan 8.

I have restarted Hearth Log.exe and Hearthstone.

Thanks for any help/advice.

**Comment by chippydip** [comment]
It looks like something might have happened to WinPCap. Normally you should see a list of your network interfaces as part of the startup messages. You can try to uninstall WinPCap (if it's installed) and re-install it. Make sure you check the box to "run at startup/login" when you install.

Let me know if that helps and I'll see if I can think of any other possible issues if it doesn't.

**Comment by celebratedsummer** [comment]
That is right.  I reinstalled WinPCap and it is working again!  Thank you!

**Comment by drgwlf** [comment]
i just downloaded/installed winpcap and hearthlog and am having issues getting it to work. seems every issue i fix brings another. thought i had it working but now my log shows this...

13:44:50: Warning: Unable to connect! 6
13:44:50: upload: 0 FAILURE 1
13:44:50: Warning: Unable to connect! 1
13:44:50: upload: 0 FAILURE 1
13:44:50: Warning: Unable to connect! 1
13:44:50: upload: 0 FAILURE 1
13:44:50: Warning: Unable to connect! 1
13:44:50: upload: 0 FAILURE 1
13:44:50: Warning: Unable to connect! 1
13:44:49: listening to \Device\NPF_{B2F1A471-B074-49D2-B5CA-DFEFB415AAB2} (Microsoft)
13:44:49: listening to \Device\NPF_{9ADA6D40-5D1D-4FF3-BC31-4EB93C67B3D7} (Realtek PCIe GBE Family Controller)
13:44:49: listening to \Device\NPF_{D4786E10-839F-4F68-A94D-02A2909847A1} (Microsoft)

any suggestions?
