### ISSUE TITLE
AppData folder not being created

### ISSUE THREAD

**Issue by SilverI3ullet** [chippydip/HearthLog#2]
When running Hearth Log for the first time I was seeing the below errors in the log when I tried to set my Hearthstone installation directory and then again when setting my Upload Key.  Neither was remembered when I reopened the application.  I created the folder manually and now the files are being stored in the folder correctly and everything works fine, it's just the initial AppData folder creation that is failing.  I'm running Windows 8 Enterprise (x64) on a domain and tried running the app as Administrator and turning UAC off, neither of which made a difference, and neither of which is needed now that the folder exists.

10:20:59: Error: Failed to create a temporary file name (error 267: the directory name is invalid.)
10:20:59: Error: can't open user configuration file.

**Comment by chippydip** [comment]
Thanks for the report!

I've just uploaded a new version (v0.2.1) which should fix this issue.
