### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by defconxt** [chippydip/HearthLog#7]
This program is awesome...the only thing I would suggest is if you could please add the option to have it automatically start up with windows? I don't know how many times I've played 2-3 games and then realized it wasn't running because I forgot to load it, lol.

Thanks for all your awesome work!

**Comment by chippydip** [comment]
This is definitely on the TODO list.

**Comment by defconxt** [comment]
cool! any eta on new releases? I know this is all volunteer work, just wondering....no pressure. Thanks!

**Comment by chippydip** [comment]
As much as I would like to add things like a proper installer and start on boot to the app, it just isn't a super-high priority right now. I'm currently getting nearly 6,000 log uploads per day on the site (roughly one upload every 15 seconds) and am fast approaching 100,000 logs in the database. At this rate, it just seems more important to spend my limited development time adding more analysis of all those logs to the site and addressing any performance bottlenecks there to ensure the site can continue to scale.

Any time I spend working on the logging app is time that's not going into improving the website. So, while this is definitely on my TODO list for the app, it's not something that seems to be hindering people from logging their games so it will probably be a while before I get around to working on it. That said, this project _is_ open source, and I would be more than happy to to accept pull requests from any other developers out that that would like to improve the logging app in this or other ways.

**Comment by coneyaw** [comment]
I have a shortcut to the .exe sitting in my start menu/startup folder, that way it boots with windows.

**Comment by defconxt** [comment]
I completely understand, chipp. It's all good.....thanks for the hard work. Also I took coneyaw's advice, and added a shortcut to it in my startup folder and it works fine. So, that is great! :) Thanks.
